# -*- coding: utf-8 -*-
"""Diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zReuCfFTvidteAdI-FIGlBFETNH6rL1h
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/diabetes.csv")

df.head()

df.info()

df.describe()

df['Outcome'].value_counts()

"""The result makes sense because the Outcome column uses 1 to represent diabetic patients."""

df['Glucose'].mean()

plt.hist(df['Glucose'])

plt.title('Distribution of Glucose Levels')
plt.xlabel('Glucose')
plt.ylabel('Frequency')

plt.show()

"""# Diabetes Dataset Analysis

# Task 2 — Diabetes Analysis

## Question 1 — How many patients have diabetes?

The result makes sense because the Outcome column uses 1 to represent diabetic patients.

# Diabetes Dataset Analysis
"""

import pandas as pd

"""# Task 2 — Diabetes Analysis

## Question 1 — How many patients have diabetes?
"""

df['Outcome'].value_counts()

"""The result makes sense because the Outcome column uses 1 to represent diabetic patients.

## Question 2 — What is the average glucose level?
"""

df['Glucose'].mean()

"""The average glucose level helps us understand the general blood sugar level of patients in the dataset.

## Question 3 — Show only female patients above age 40
"""

df[(df['Age'] > 40)].head()

"""EXPLANATION
This filter helps identify older patients who may have a higher risk of diabetes.
what does this mean

## Question 4 — Group by outcome and show average BMI
"""

df.groupby('Outcome')['BMI'].mean()

"""This comparison helps show whether BMI differs between diabetic and non-diabetic patients.

## Question 5 — Remove rows with zero glucose values
"""

original_rows = df.shape[0]

df_cleaned = df[df['Glucose'] != 0]

new_rows = df_cleaned.shape[0]

removed_rows = original_rows - new_rows

print(removed_rows)

"""Removing zero glucose values improves data quality because a glucose value of zero is unrealistic.

# Task 3 — Data Visualization

## Histogram of Glucose Levels
"""

plt.hist(df['Glucose'])

plt.title('Distribution of Glucose Levels')
plt.xlabel('Glucose Level')
plt.ylabel('Frequency')

plt.show()

"""The histogram shows how glucose levels are distributed among patients.

## Scatter Plot of BMI vs Glucose
"""

plt.scatter(df['BMI'], df['Glucose'])

plt.title('BMI vs Glucose')
plt.xlabel('BMI')
plt.ylabel('Glucose')

plt.show()

"""The scatter plot helps show the relationship between BMI and glucose levels.

## Bar Chart of Diabetes Outcome
"""

df['Outcome'].value_counts().plot(kind='bar')

plt.title('Diabetes Outcome Count')
plt.xlabel('Outcome')
plt.ylabel('Count')

plt.show()

"""The bar chart compares the number of diabetic and non-diabetic patients.

## Box Plot of Age Distribution
"""

plt.boxplot(df['Age'])

plt.title('Age Distribution')
plt.ylabel('Age')

plt.show()

"""The box plot shows the spread and possible outliers in patient ages.

## Line Chart of Glucose Levels
"""

df['Glucose'].head(20).plot(kind='line')

plt.title('Glucose Levels')
plt.xlabel('Patient Index')
plt.ylabel('Glucose')

plt.show()

"""The line chart shows how glucose levels vary across different patients.

# Task 3 — Data Visualization

## Histogram of Glucose Levels
"""

plt.hist(df['Glucose'])

plt.title('Distribution of Glucose Levels')
plt.xlabel('Glucose Level')
plt.ylabel('Frequency')

plt.show()

"""The histogram shows how glucose levels are distributed among patients.

## Scatter Plot of BMI vs Glucose
"""

plt.scatter(df['BMI'], df['Glucose'])

plt.title('BMI vs Glucose')
plt.xlabel('BMI')
plt.ylabel('Glucose')

plt.show()

"""The scatter plot helps show the relationship between BMI and glucose levels.

## Bar Chart of Diabetes Outcome
"""

df['Outcome'].value_counts().plot(kind='bar')

plt.title('Diabetes Outcome Count')
plt.xlabel('Outcome')
plt.ylabel('Count')

plt.show()

"""The bar chart compares the number of diabetic and non-diabetic patients.

## Box Plot of Age Distribution
"""

plt.boxplot(df['Age'])

plt.title('Age Distribution')
plt.ylabel('Age')

plt.show()

"""The box plot shows the spread and possible outliers in patient ages.

## Line Chart of Glucose Levels
"""

df['Glucose'].head(20).plot(kind='line')

plt.title('Glucose Levels')
plt.xlabel('Patient Index')
plt.ylabel('Glucose')

plt.show()

"""The line chart shows how glucose levels vary across different patients.

# Seaborn Styled Charts

## Seaborn Histogram
"""

sns.histplot(df['Glucose'])

plt.title('Distribution of Glucose Levels')
plt.xlabel('Glucose Level')
plt.ylabel('Frequency')

plt.show()

"""## Seaborn Scatter Plot"""

sns.scatterplot(x='BMI', y='Glucose', data=df)

plt.title('BMI vs Glucose')
plt.xlabel('BMI')
plt.ylabel('Glucose')

plt.show()

"""## Seaborn Bar Chart"""

sns.countplot(x='Outcome', data=df)

plt.title('Diabetes Outcome Count')
plt.xlabel('Outcome')
plt.ylabel('Count')

plt.show()

"""## Seaborn Box Plot"""

sns.boxplot(y='Age', data=df)

plt.title('Age Distribution')
plt.ylabel('Age')

plt.show()

"""## Seaborn Line Chart"""

sns.lineplot(data=df['Glucose'].head(20))

plt.title('Glucose Levels')
plt.xlabel('Patient Index')
plt.ylabel('Glucose')

plt.show()

"""## Which Version I Prefer

I prefer the seaborn charts because they look cleaner and more visually appealing. The styling makes the charts easier to read and understand.

# Task 4 — Data Story

## Questions I Want to Answer

1. Does glucose level affect diabetes outcome?

2. Is BMI linked to diabetes outcome?

3. Which age group has the highest diabetes rate?

## Question 1 — Does glucose level affect diabetes outcome?
"""

sns.boxplot(x='Outcome', y='Glucose', data=df)

plt.title('Glucose Levels by Diabetes Outcome')
plt.xlabel('Outcome')
plt.ylabel('Glucose Level')

plt.show()

"""Patients with diabetes had higher glucose levels compared to non-diabetic patients.

## Question 2 — Is BMI linked to diabetes outcome?
"""

sns.boxplot(x='Outcome', y='BMI', data=df)

plt.title('BMI by Diabetes Outcome')
plt.xlabel('Outcome')
plt.ylabel('BMI')

plt.show()

"""Patients with diabetes generally showed higher BMI values than non-diabetic patients.

## Question 3 — Which age group has the highest diabetes rate?
"""

sns.histplot(data=df, x='Age', hue='Outcome', multiple='stack')

plt.title('Age Distribution by Diabetes Outcome')
plt.xlabel('Age')
plt.ylabel('Count')

plt.show()

"""Middle-aged patients appeared to have a higher rate of diabetes compared to younger patients.

# What I Would Explore Next

I would further investigate how insulin levels affect diabetes risk. I would also combine this dataset with lifestyle or exercise datasets to discover more health patterns. Additional information such as diet, physical activity, and family medical history would improve the analysis.
"""